# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/2ee5f08e-05f1-4ac8-bb6d-8946da15937b";
      fsType = "btrfs";
      options = [
        "subvol=root"
        "compress=zstd"
      ];
    };

  fileSystems."/var/lib" =
    { device = "/dev/disk/by-uuid/2ee5f08e-05f1-4ac8-bb6d-8946da15937b";
      fsType = "btrfs";
      options = [
        "subvol=var/lib"
        "compress=zstd"
      ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/2ee5f08e-05f1-4ac8-bb6d-8946da15937b";
      fsType = "btrfs";
      options = [
        "subvol=nix"
        "compress=zstd"
        "noatime"
      ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/2ee5f08e-05f1-4ac8-bb6d-8946da15937b";
      fsType = "btrfs";
      options = [
        "subvol=swap"
        "noatime"
      ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2877-1C39";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [{
    device = "/swap/swapfile";
    size = 8*1024;
  }];

  hardware.enableRedistributableFirmware = true;
  services = {
    thermald.enable = true;
    fwupd.enable = true;
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
